Piso 2022 0875
johansantana/Hotel pull request #15
Opened 2024-02-14 23:16 UTC by DarlingJunior28

Rama-Piso

2024-02-14 23:23 UTC, johansantana requested changes

2024-02-14 23:23 UTC, johansantana commented on Hotel.Domain/Entities/Pisos.cs
En lugar de `Pisos` colocale `Piso` a la entidad.

2024-02-14 23:23 UTC, johansantana commented on Hotel.Domain/Hotel.Domain.csproj
Añade de nuevo esa línea

2024-02-14 23:23 UTC, johansantana commented on Hotel.Infrastructure/Context/HotelContext.cs
Coloca `pisos` como `Pisos`

2024-02-14 23:23 UTC, johansantana commented on Hotel.Infrastructure/Interfaces/IPiso.cs
No dejes los  métodos simplemente como `Save`, `Remove`, etc. Tienes que ponerle `SavePiso`, `RemovePiso`...

2024-02-14 23:23 UTC, johansantana commented on Hotel.Infrastructure/Repositories/RepositoryPiso.cs
Asegúrate de guardar los cambios con `hotelContext.saveChanges()`

2024-02-15 00:07 UTC, DarlingJunior28 commented
Entendido.🫡

El El mié, 14 de feb. de 2024 a la(s) 7:24 p.m., Johan Santana <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On Hotel.Domain/Entities/Pisos.cs
> <https://github.com/johansantana/Hotel/pull/15#discussion_r1490179560>:
>
> En lugar de Pisos colocale Piso a la entidad.
> ------------------------------
>
> On Hotel.Domain/Hotel.Domain.csproj
> <https://github.com/johansantana/Hotel/pull/15#discussion_r1490179937>:
>
> Añade de nuevo esa línea
> ------------------------------
>
> On Hotel.Infrastructure/Context/HotelContext.cs
> <https://github.com/johansantana/Hotel/pull/15#discussion_r1490180781>:
>
> Coloca pisos como Pisos
> ------------------------------
>
> On Hotel.Infrastructure/Interfaces/IPiso.cs
> <https://github.com/johansantana/Hotel/pull/15#discussion_r1490181507>:
>
> No dejes los métodos simplemente como Save, Remove, etc. Tienes que
> ponerle SavePiso, RemovePiso...
> ------------------------------
>
> On Hotel.Infrastructure/Repositories/RepositoryPiso.cs
> <https://github.com/johansantana/Hotel/pull/15#discussion_r1490183192>:
>
> Asegúrate de guardar los cambios con hotelContext.saveChanges()
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/johansantana/Hotel/pull/15#pullrequestreview-1881480321>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BD4VJU7VVNANLIKR3RP5HB3YTVBRHAVCNFSM6AAAAABDJIYG6OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBRGQ4DAMZSGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-15 21:02 UTC, closed without merging