Piso 2022 0875
johansantana/Hotel pull request #16
Opened 2024-02-15 21:16 UTC by DarlingJunior28

Verificar ahora

2024-02-15 21:46 UTC, johansantana requested changes

2024-02-15 21:46 UTC, johansantana commented on Hotel.Domain/Hotel.Domain.csproj
Ese archivo de `Hotel.Domain.csproj` le estás quitando una linea.

2024-02-15 21:46 UTC, johansantana commented on Hotel.Infrastructure/Context/HotelContext.cs
Aqui en ese archivo pon `Pisos` en lugar de `pisos`

2024-02-15 21:46 UTC, johansantana commented on Hotel.Infrastructure/Models/Piso.cs
El nombre del archivo ponle `PisoModel`.

2024-02-16 22:13 UTC, johansantana requested changes
Revisa los archivos que mandas antes de hacer el commit, porque estás modificando archivos que se salen de lo que te toca, en este caso: `BaseEntity.cs`, `Categoria.cs`, `RolUsuario.cs`, `Usuario.cs`, `Hotel.Domain.csproj`.

2024-02-16 22:13 UTC, johansantana commented on Hotel.Infrastructure/Models/PisoModel.cs
Aquí solo tenías que cambiar el nombre del archivo, la clase se debería seguir llamando Piso

2024-02-16 22:21 UTC, DarlingJunior28 commented
Pero, yo solo hago las modificaciones correspondientes.

El El vie, 16 de feb. de 2024 a la(s) 6:13 p.m., Johan Santana <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> Revisa los archivos que mandas antes de hacer el commit, porque estás
> modificando archivos que se salen de lo que te toca, en este caso:
> BaseEntity.cs, Categoria.cs, RolUsuario.cs, Usuario.cs,
> Hotel.Domain.csproj.
> ------------------------------
>
> On Hotel.Infrastructure/Models/PisoModel.cs
> <https://github.com/johansantana/Hotel/pull/16#discussion_r1493028481>:
>
> Aquí solo tenías que cambiar el nombre del archivo, la clase se debería
> seguir llamando Piso
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/johansantana/Hotel/pull/16#pullrequestreview-1886147676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BD4VJU4Z6ASCU6L75RXXNETYT7KYFAVCNFSM6AAAAABDK7E5C6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBWGE2DONRXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-16 22:22 UTC, johansantana commented
Fíjate que cambiaste unos archivos en los commits que hiciste

2024-02-16 22:27 UTC, johansantana requested changes
Aún falta corregir los cambios que hiciste en los archivos que te mencione. Haz un commit revirtiendo esos cambios, puedes copiar y pegar el contenido que tienen en la rama `main` para eso.

2024-02-16 22:27 UTC, johansantana commented on Hotel.Infrastructure/Models/Piso.cs
También me fije que le pusiste `abstract`.

2024-03-13 00:27 UTC, closed without merging

2024-03-13 00:29 UTC, DarlingJunior28 commented
Ya yo tengo todo eso realizado, me falta algunos reajustes en la api mañana
lo subo todo junto. Lo tengo en la PC del trabajo.💀💀💀

El El mar, 12 mar 2024 a la(s) 8:28 p.m., Johan Santana <
***@***.***> escribió:

> Closed #16 <https://github.com/johansantana/Hotel/pull/16>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/johansantana/Hotel/pull/16#event-12096339129>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BD4VJUZPSGBWE4EC6M65WJTYX6MRLAVCNFSM6AAAAABDK7E5C6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGA4TMMZTHEYTEOI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>